
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3008
    command: npm run dev
